---
name: CWTools CI

'on':
  - pull_request
  - push

jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cwtools/cwtools-action@v1.1.0
        with:
          game: hoi4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v1.1.0
        with:
          name: cwtools_output
          path: output.json
